// Postgres adapter for the Task API repository interface (the A3 storage engine).
// Implements the same interface as repository/sqlite.js — the route layer in
// index.js never touches SQL, so swapping engines changes only this file.
//
// Every query is parameterized ($1, $2, ...): values are passed separately to
// the driver, never glued into the SQL string.
const { Pool } = require('pg');

// The three example tasks every fresh database starts with. Inserted only when
// the table is empty, so restarting the server never duplicates them.
const SEED_TASKS = [
  { title: 'Buy groceries', done: false },
  { title: 'Walk the dog', done: true },
  { title: 'Read a book', done: false },
];

// Columns every read selects, in a fixed order — the API's JSON shape.
const TASK_COLUMNS = 'id, title, done, created_at, updated_at';

// Postgres timestamptz values arrive as JS Date objects. Format them as
// 'YYYY-MM-DD HH:MM:SS' (UTC) — the exact string SQLite's datetime('now')
// produced, so the API output stays byte-identical to A2.
function formatTimestamp(date) {
  return date.toISOString().slice(0, 19).replace('T', ' ');
}

// Normalize a raw driver row into the JSON shape the API returns.
// Postgres gives real booleans for `done`; timestamps are formatted above.
function rowToTask(row) {
  return {
    id: row.id,
    title: row.title,
    done: Boolean(row.done),
    created_at: formatTimestamp(row.created_at),
    updated_at: formatTimestamp(row.updated_at),
  };
}

// Factory: creates a connection pool from the connection string and returns
// the repository. The pool is lazy — no connection happens until the first
// query, so ensureSchemaAndSeed() at boot is also the connectivity check
// (a failure there means "fail fast": log and exit, never half-run).
function createTaskRepository(connectionString) {
  const pool = new Pool({ connectionString });

  return {
    // Boot: create the table if missing, then seed the three example tasks
    // only when the table is empty. Runs once at startup, before listening.
    // timestamptz stores UTC-aware timestamps; the adapter formats them.
    async ensureSchemaAndSeed() {
      await pool.query(`
        CREATE TABLE IF NOT EXISTS tasks (
          id serial PRIMARY KEY,
          title text NOT NULL,
          done boolean NOT NULL DEFAULT false,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        )
      `);
      const { rows } = await pool.query('SELECT COUNT(*)::int AS count FROM tasks');
      if (rows[0].count === 0) {
        // No explicit ids: on an empty table serial assigns 1, 2, 3 in order.
        for (const task of SEED_TASKS) {
          await pool.query('INSERT INTO tasks (title, done) VALUES ($1, $2)', [
            task.title,
            task.done,
          ]);
        }
      }
    },

    // GET /tasks — optional ?done= / ?search= filters narrow the SQL itself.
    async list({ done, search } = {}) {
      let sql = `SELECT ${TASK_COLUMNS} FROM tasks WHERE 1=1`;
      const params = [];
      if (done !== undefined) {
        params.push(done);
        sql += ` AND done = $${params.length}`;
      }
      if (search !== undefined) {
        params.push(`%${search.toLowerCase()}%`);
        sql += ` AND LOWER(title) LIKE $${params.length}`;
      }
      sql += ' ORDER BY id';
      const { rows } = await pool.query(sql, params);
      return rows.map(rowToTask);
    },

    // GET /tasks/:id — null means "unknown id" and the route turns it into 404.
    async getById(id) {
      const { rows } = await pool.query(`SELECT ${TASK_COLUMNS} FROM tasks WHERE id = $1`, [id]);
      return rows[0] ? rowToTask(rows[0]) : null;
    },

    // POST /tasks — RETURNING hands back the new row (id and timestamps
    // generated by the database) without a second query.
    async create(title) {
      const { rows } = await pool.query(
        `INSERT INTO tasks (title, done) VALUES ($1, false) RETURNING ${TASK_COLUMNS}`,
        [title]
      );
      return rowToTask(rows[0]);
    },

    // PUT /tasks/:id — partial update: merge the patch over the stored row,
    // bump updated_at. Returns null when the id is unknown (route → 404).
    async update(id, patch) {
      const { rows } = await pool.query(`SELECT ${TASK_COLUMNS} FROM tasks WHERE id = $1`, [id]);
      if (!rows[0]) return null;
      const title = patch.title !== undefined ? patch.title : rows[0].title;
      const done = patch.done !== undefined ? patch.done : rows[0].done;
      const { rows: updated } = await pool.query(
        `UPDATE tasks SET title = $1, done = $2, updated_at = now() WHERE id = $3 RETURNING ${TASK_COLUMNS}`,
        [title, done, id]
      );
      return rowToTask(updated[0]);
    },

    // DELETE /tasks/:id — true when a row was actually removed (route → 204),
    // false when the id was unknown (route → 404).
    async remove(id) {
      const result = await pool.query('DELETE FROM tasks WHERE id = $1', [id]);
      return result.rowCount > 0;
    },

    // GET /stats — counts computed in SQL, not in JavaScript. COUNT(*) is
    // int8 (returned as a string by pg), so cast to int for JSON number parity.
    async stats() {
      const { rows } = await pool.query(`
        SELECT
          COUNT(*)::int AS total,
          COUNT(*) FILTER (WHERE done)::int AS done,
          COUNT(*) FILTER (WHERE NOT done)::int AS open
        FROM tasks
      `);
      return rows[0];
    },

    // POST /reset — wipe the table and restore the three example tasks.
    // RESTART IDENTITY resets the serial sequence; inserting without ids then
    // yields 1, 2, 3 again — matching A2's reseed behaviour, and keeping the
    // next POST from colliding with the reseeded ids.
    async reset() {
      await pool.query('TRUNCATE tasks RESTART IDENTITY');
      for (const task of SEED_TASKS) {
        await pool.query('INSERT INTO tasks (title, done) VALUES ($1, $2)', [
          task.title,
          task.done,
        ]);
      }
      const { rows } = await pool.query(`SELECT ${TASK_COLUMNS} FROM tasks ORDER BY id`);
      return rows.map(rowToTask);
    },

    // Health probe (SELECT 1) used by the /health endpoint.
    async ping() {
      await pool.query('SELECT 1');
    },
  };
}

module.exports = { createTaskRepository };
